# Generated by Django 3.2.9 on 2021-11-17 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre *')),
                ('legal_name', models.CharField(default='', max_length=80, verbose_name='Razón social *')),
                ('nif', models.CharField(default='', max_length=30, verbose_name='NIF/DNI *')),
                ('billing_adress', models.CharField(default='', max_length=300, verbose_name='Dirección de facturación *')),
                ('phone_number', models.CharField(default='', max_length=30, verbose_name='Teléfono de contacto *')),
                ('mail', models.CharField(default='', max_length=80, verbose_name='Correo electrónico *')),
                ('active_flag', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('stakeholder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stakeholders.stakeholder')),
                ('delivery_adress', models.CharField(default='', max_length=300, verbose_name='Dirección de entrega *')),
                ('billing_time', models.IntegerField(default=0, verbose_name='Período de cobro (días)')),
            ],
            bases=('stakeholders.stakeholder',),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('stakeholder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stakeholders.stakeholder')),
                ('delivery_method', models.CharField(choices=[('collect', 'Recogida de pedido'), ('selfservice', 'Autoservicio'), ('delivery', 'A domicilio')], max_length=80, verbose_name='Método de entrega:')),
                ('delivery_adress', models.CharField(default='', max_length=300, verbose_name='Dirección de recogida/envío *')),
                ('payment_method', models.CharField(choices=[('transfer', 'Transferencia'), ('cash', 'Efectivo'), ('card', 'Tarjeta'), ('bizum', 'Bizum'), ('paypal', 'Paypal')], max_length=80, verbose_name='Método de pago *')),
                ('payment_time', models.IntegerField(default=0, verbose_name='Período de pago (días)')),
            ],
            bases=('stakeholders.stakeholder',),
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre *')),
                ('phone_number', models.CharField(default='', max_length=30, verbose_name='Teléfono de contacto *')),
                ('mail', models.CharField(default='', max_length=80, verbose_name='Correo electrónico *')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholders.stakeholder', verbose_name='Ogranización')),
            ],
        ),
    ]
