# Generated by Django 3.2.9 on 2021-11-19 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stakeholders', '0001_initial'),
        ('products', '0005_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre *')),
                ('description', models.CharField(blank=True, default='', max_length=600, verbose_name='Detalles del evento')),
                ('order_type', models.CharField(choices=[('catering', 'Catering'), ('festival', 'Festival'), ('wedding', 'Boda')], default='', max_length=30, verbose_name='Tipo de pedido *')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de inicio *')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de finalización *')),
                ('labour_days', models.IntegerField(default=1, verbose_name='Días laborables * ')),
                ('menu_ammount', models.IntegerField(default=1, verbose_name='Número de menús')),
                ('menu_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Coste de menús (€)')),
                ('extra_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Coste de extras (€)')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Coste total por menú (€)')),
                ('completed_flag', models.BooleanField(default=False, verbose_name='Completado')),
                ('completed_comments', models.TextField(blank=True, verbose_name='Observaciones final de evento')),
                ('active_flag', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stakeholders.client', verbose_name='Cliente *')),
            ],
        ),
        migrations.CreateModel(
            name='ConcreteMenuInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_ammount', models.IntegerField(blank=True, default='1', verbose_name='Número de menús *')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=7, verbose_name='Coste total (€)')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.menu', verbose_name='Menú *')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Pedido *')),
            ],
        ),
        migrations.CreateModel(
            name='ConcreteExtraInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_ammount', models.IntegerField(blank=True, default='1', verbose_name='Número de extras *')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=7, verbose_name='Coste total (€)')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.extra', verbose_name='Extra *')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Pedido *')),
            ],
        ),
    ]
