# Generated by Django 3.2.9 on 2021-11-19 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='worker_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Coste de menús (€)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Coste total (€)'),
        ),
        migrations.CreateModel(
            name='ConcreteWorkerInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de inicio *')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de finalización *')),
                ('hours_ammount', models.IntegerField(blank=True, default='1', verbose_name='Número de horas *')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=7, verbose_name='Coste total (€)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Pedido *')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.worker', verbose_name='Trabajador *')),
            ],
        ),
    ]
