# Generated by Django 3.2.9 on 2021-11-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211119_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='concreteworkerinorder',
            name='task',
            field=models.CharField(choices=[('production', 'Producción'), ('camarera', 'Camarera'), ('transport', 'Transporte')], default='', max_length=30, verbose_name='Tarea *'),
        ),
        migrations.AlterField(
            model_name='order',
            name='worker_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Coste de trabajadores (€)'),
        ),
    ]
