# Generated by Django 3.2.9 on 2021-11-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211119_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.CharField(blank=True, default='', max_length=600, verbose_name='Dirección de entrega *'),
        ),
        migrations.AddField(
            model_name='order',
            name='feedback_flag',
            field=models.BooleanField(default=False, verbose_name='Feedback'),
        ),
        migrations.AddField(
            model_name='order',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Facturación sin IVA (€)'),
        ),
        migrations.AddField(
            model_name='order',
            name='planned_flag',
            field=models.BooleanField(default=False, verbose_name='Planificado'),
        ),
        migrations.AddField(
            model_name='order',
            name='preparation_comments',
            field=models.TextField(blank=True, verbose_name='Comentarios sobre preparación'),
        ),
        migrations.AddField(
            model_name='order',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Beneficio (€)'),
        ),
        migrations.AddField(
            model_name='order',
            name='profit_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, verbose_name='Rentabilidad (%)'),
        ),
        migrations.AlterField(
            model_name='concreteworkerinorder',
            name='hours_ammount',
            field=models.IntegerField(blank=True, default='1', verbose_name='Número de horas (en decimal)'),
        ),
    ]
