# Generated by Django 3.2.9 on 2021-11-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20211122_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='extra_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Coste de extras (€)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Facturación sin IVA (€)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Coste de menús (€)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Beneficio (€)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='profit_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Rentabilidad (%)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Coste total (€)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='worker_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Coste de trabajadores (€)'),
        ),
    ]
