# Generated by Django 3.2.9 on 2021-11-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Nombre *')),
                ('second_name', models.CharField(max_length=80, verbose_name='Appelido *')),
                ('worker_type', models.CharField(choices=[('partner', 'Socia'), ('extern', 'Externa')], default='', max_length=20, verbose_name='Tipo de trabajador *')),
                ('driving_license_flag', models.BooleanField(default=False, verbose_name='Carnet de conducir')),
                ('own_car_flag', models.BooleanField(default=False, verbose_name='Coche propio')),
                ('phone_number', models.CharField(choices=[('partner', 'Socia'), ('extern', 'Externa')], default='', max_length=20, verbose_name='Teléfono *')),
                ('mail', models.CharField(default='', max_length=80, verbose_name='Correo electrónico *')),
                ('hour_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Coste por hora (€)')),
                ('active_flag', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
        ),
    ]
