# Generated by Django 3.2.9 on 2021-11-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='Teléfono *'),
        ),
    ]
