# Generated by Django 3.2.9 on 2021-11-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_worker_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_type',
            field=models.CharField(choices=[('partner', 'Socia'), ('worker', 'Trabajadora'), ('extern', 'Externa')], default='', max_length=20, verbose_name='Tipo de trabajador *'),
        ),
    ]
