# Generated by Django 3.2.9 on 2021-11-17 10:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descripción')),
                ('kcal', models.IntegerField(blank=True, verbose_name='Calorías (kcal/100g)')),
                ('ingredient_type', models.CharField(choices=[('fruit', 'Fruta'), ('vegetable', 'Verduras'), ('cereal', 'Cereales'), ('legume', 'Legumbres'), ('dried_fruit', 'Frutos secos'), ('meat', 'Carnes'), ('fish', 'Pescados y mariscos'), ('lactic', 'Lácticos'), ('eggs', 'Huevo y derivados'), ('species', 'Especias y condimentos'), ('infusions', 'Infusiones'), ('oils', 'Aceites y grasas vegetales'), ('water', 'Agua'), ('others', 'Otros')], max_length=30, verbose_name='Tipo de ingrediente')),
                ('allergens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('spicy', 'Picante'), ('gluten', 'Gluten'), ('dried_fruits', 'Frutos secos'), ('mollusks', 'Moluscos'), ('fish', 'pescado'), ('crustacean', 'Crustáceos'), ('sesame', 'Sésamo'), ('lactosa', 'Lactosa'), ('mustard', 'Mostaza'), ('celery', 'Apio'), ('peanut', 'Cacahuete'), ('sulfit', 'Sulfitos'), ('soy', 'Soja'), ('lupins', 'Altramuces')], max_length=30), blank=True, size=None, verbose_name='Alérgenos')),
                ('conservation_method', models.CharField(choices=[('storage', 'Almacén'), ('nevera', 'Nevera'), ('freezer', 'Congelador')], default='No definido', max_length=30, verbose_name='Conservación')),
                ('lifetime', models.IntegerField(blank=True, verbose_name='Vida útil (días)')),
                ('active_flag', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
        ),
        migrations.CreateModel(
            name='ConcreteIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=80, verbose_name='Proveedor')),
                ('pack_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Kg o L por paquete')),
                ('price_pack', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Precio por paquete')),
                ('price_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Precio por kg o L')),
                ('active_flag', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ingredient', verbose_name='Ingrediente')),
            ],
        ),
    ]
