# Generated by Django 3.2.9 on 2021-11-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='concreteingredient',
            name='pack_kg',
        ),
        migrations.RemoveField(
            model_name='concreteingredient',
            name='price_kg',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='allergens',
        ),
        migrations.AddField(
            model_name='concreteingredient',
            name='description',
            field=models.CharField(default='', max_length=300, verbose_name='Descripción del producto *'),
        ),
        migrations.AddField(
            model_name='concreteingredient',
            name='measuring_unit',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('l', 'Litro'), ('ud', 'Unidad')], default='kg', max_length=5, verbose_name='Unidad de medida'),
        ),
        migrations.AddField(
            model_name='concreteingredient',
            name='pack_units',
            field=models.DecimalField(blank=True, decimal_places=2, default='1', max_digits=7, verbose_name=' Formato (kg,litro o uds. por paquete) *'),
        ),
        migrations.AddField(
            model_name='concreteingredient',
            name='price_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Precio por unidad de medida'),
        ),
        migrations.AddField(
            model_name='concreteingredient',
            name='reference',
            field=models.CharField(default='', max_length=30, verbose_name='Referencia producto *'),
        ),
        migrations.AlterField(
            model_name='concreteingredient',
            name='price_pack',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Precio (sin IVA)*'),
        ),
        migrations.AlterField(
            model_name='concreteingredient',
            name='provider',
            field=models.CharField(max_length=80, verbose_name='Proveedor *'),
        ),
        migrations.AddField(
            model_name='concreteingredient',
            name='allergens',
            field=models.ManyToManyField(blank=True, max_length=80, to='products.Allergen', verbose_name='Alérgenos y dietas especiales *'),
        ),
    ]
