# Generated by Django 3.2.9 on 2021-11-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Emoticono'),
        ),
    ]
