# Generated by Django 3.2.9 on 2021-11-16 15:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='conservation_method',
            field=models.CharField(choices=[('storage', 'Almacén'), ('nevera', 'Nevera'), ('freezer', 'Congelador')], default='No definido', max_length=30, verbose_name='Conservación'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='allergens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('spicy', 'Picante'), ('gluten', 'Gluten'), ('dried_fruits', 'Frutos secos'), ('mollusks', 'Moluscos'), ('fish', 'pescado'), ('crustacean', 'Crustáceos'), ('sesame', 'Sésamo'), ('lactosa', 'Lactosa'), ('mustard', 'Mostaza'), ('celery', 'Apio'), ('peanut', 'Cacahuete'), ('sulfit', 'Sulfitos'), ('soy', 'Soja'), ('lupins', 'Altramuces')], max_length=30), blank=True, size=None, verbose_name='Alérgenos'),
        ),
    ]
