# Generated by Django 3.2.9 on 2021-11-18 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_allergen_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre del recurso')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='Descripción')),
                ('resource_type', models.CharField(choices=[('person', 'Personal (hora)'), ('machine', 'Máquina (hora)'), ('transport', 'Transporte (hora)')], max_length=30, verbose_name='Tipo de recurso')),
                ('price_unit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Precio por unidad')),
                ('active_flag', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
        ),
        migrations.CreateModel(
            name='ConcreteResourceInRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammout_per_serving', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=7, verbose_name='Cantidad por ración *')),
                ('cost_per_serving', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=7, verbose_name='Coste por ración (€)')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.recipe', verbose_name='Receta')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.resource', verbose_name='Recurso *')),
            ],
        ),
    ]
