# Generated by Django 3.2.9 on 2021-11-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211117_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergen',
            name='name',
            field=models.CharField(default='', max_length=80, verbose_name='Nombre'),
        ),
    ]
