# Generated by Django 3.2.9 on 2021-11-17 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211116_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='active_flag',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='created',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='price_kg',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='provider',
        ),
        migrations.CreateModel(
            name='ConcreteIngredient',
            fields=[
                ('ingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.ingredient')),
                ('provider', models.CharField(max_length=80, verbose_name='Proveedor')),
                ('pack_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Kg o L por paquete')),
                ('price_pack', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Precio por paquete')),
                ('price_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Precio por kg o L')),
                ('active_flag', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            bases=('products.ingredient',),
        ),
    ]
