# Generated by Django 3.2.9 on 2021-11-18 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_concreteresourceinrecipe_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre *')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='Descripción')),
                ('menu_type', models.CharField(choices=[('coffee_break', 'Coffee Break'), ('festival', 'Ferias y festivales'), ('wedding', 'Bodas'), ('experiencie', 'Experiencia gastronómica')], default='', max_length=30, verbose_name='Tipo de menú *')),
                ('min_servings', models.IntegerField(default=1, verbose_name='Raciones mínimas *')),
                ('preparation_time', models.IntegerField(blank=True, verbose_name='Tiempo de preparación (min)')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Coste total por menú (€)')),
                ('active_flag', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('drink', 'Bebidas'), ('hot_drink', 'Bebidas calientes'), ('snacks', 'Snacks y entrantes'), ('main', 'Principales'), ('sauces', 'Salsas'), ('desserts', 'Postres y dulces')], default='', max_length=30, verbose_name='Tipo de receta*'),
        ),
        migrations.CreateModel(
            name='ConcreteRecipeInMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rations_per_menu', models.IntegerField(blank=True, default='1', verbose_name='Raciones por menú *')),
                ('cost_per_menu', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=7, verbose_name='Coste por menú (€)')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.menu', verbose_name='Menú *')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.recipe', verbose_name='Receta *')),
            ],
        ),
    ]
