# Generated by Django 3.2.9 on 2021-11-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_allergen_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre *')),
                ('description', models.CharField(default='', max_length=300, verbose_name='Descripción *')),
                ('recipe_type', models.CharField(choices=[('drink', 'Bebidas'), ('hot_drink', 'Bebidas calientes'), ('snacks', 'Snacks y entrantes'), ('main', 'Principales'), ('sauces', 'Salsas'), ('desserts', 'Postres y dulces')], default='', max_length=30, verbose_name='Referencia producto *')),
                ('min_servings', models.IntegerField(default=1, max_length=3, verbose_name='Raciones mínimas *')),
                ('preparation_time', models.TimeField(blank=True, verbose_name='Tiempo de preparación')),
                ('ingredient_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Coste ingredientes por ración')),
                ('resource_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Coste ingredientes por ración')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Coste total por ración')),
                ('active_flag', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
        ),
        migrations.CreateModel(
            name='ConcreteIngredientInRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammout_per_serving', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=7, verbose_name='Cantidad por ración (kg,litro o uds.) *')),
                ('concrete_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.concreteingredient', verbose_name='Ingrediente')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.recipe', verbose_name='Receta')),
            ],
        ),
    ]
