# Generated by Django 3.2.9 on 2021-11-17 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0001_initial'),
        ('products', '0004_concreteingredientinrecipe_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concreteingredient',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stakeholders.provider', verbose_name='Proveedor *'),
        ),
    ]
