# Generated by Django 3.2.9 on 2021-11-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211118_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre *')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='Descripción')),
                ('extra_type', models.CharField(choices=[('personal', 'Personal (hora)'), ('transport', 'Transporte (hora)'), ('dishes', 'Vajilla'), ('decoration', 'Decoración'), ('rent', 'Alquiler')], default='', max_length=30, verbose_name='Tipo de extra *')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Coste por unidad (€)*')),
                ('active_flag', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
        ),
    ]
