# Generated by Django 3.2.9 on 2021-11-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_concreteingredient_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='concreteingredientinrecipe',
            name='cost_per_serving',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=7, verbose_name='Cantidad por ración (kg,litro o uds.) *'),
        ),
    ]
