# Generated by Django 3.2.9 on 2021-11-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='preparation_time',
        ),
        migrations.DeleteModel(
            name='ConcreteResourceInRecipe',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
