# Generated by Django 3.2.9 on 2021-11-18 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_concreteingredientinrecipe_cost_per_serving'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergen',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='concreteingredient',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='concreteingredientinrecipe',
            name='concrete_ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.concreteingredient', verbose_name='Ingrediente *'),
        ),
        migrations.AlterField(
            model_name='concreteingredientinrecipe',
            name='cost_per_serving',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=7, verbose_name='Coste por ración (€)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Coste ingredientes por ración (€)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='min_servings',
            field=models.IntegerField(default=1, verbose_name='Raciones mínimas *'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.IntegerField(blank=True, verbose_name='Tiempo de preparación (min)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='resource_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Coste recursos por ración (€) *'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Coste total por ración (€)'),
        ),
    ]
