# Generated by Django 3.2.9 on 2021-11-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211122_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient_cost',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='resource_cost',
        ),
    ]
